version: "3.8"

services:
  top-movies-prod:
    image: top-movies-prod
    container_name: top-movies-prod
    build:
      dockerfile: docker/prod/Dockerfile
      context: .
    expose:
      - 80
    volumes:
      - "${PWD}:/app"
      - "/app/node_modules"
    networks:
      - top-movies

networks:
  top-movies:
    external: true
